## 平均值作業

In [3]:
class Student:
    def __init__(self, name):
        self.name, self.grades = name, []
    def append_grade(self, grade):
        self.grades.append(grade)
    def average(self):
        return sum(self.grades) / len(self.grades)
    def letter_grade(self):
        average = self.average()
        for value, grade in (90, "A"), (80, "B"), (70, "C"), (60, "D"):
            if average >= value:
                return grade
        else:
            return "F"
def print_report(a_class):
    print()
    print('班級清單')
    print()
    for student in a_class:
        print(f'學生: {student.name} 成績:{student.grades} 平均成績: {student.average():.2f}  等第: { student.letter_grade()}')
    print()
    print(f'班級平均成績 {class_average(a_class):.2f}')

def class_average(a_class):
    return sum(student.average() for student in a_class) / len(a_class)

print('班上學生考試資訊:')
a_class = []  # "class" by itself is a reserved word in Python, avoid using
while True:
    print()
    print(f'學生人數{len(a_class)}人')
    another_student = input('輸入新的學生資料 (y/n) ? ')
    if another_student[0].lower() != 'y':
        break
    print()
    student_name = input('輸入學生姓名: ')
    a_class.append(Student(student_name))
    print()
    print('學生:', student_name)
    print('-------------------')
    number_of_tests = int(input('考試科目有幾科? : '))
    for test_num in range(1, number_of_tests+1):
        print(f'科目 {test_num} 分數', end='')
        score = float(input(' : '))
        if score < 0:
            break
        a_class[-1].append_grade(score) 
print_report(a_class)


班上學生考試資訊:

學生人數0人
輸入新的學生資料 (y/n) ? y

輸入學生姓名: Ken

學生: Ken
-------------------
考試科目有幾科? : 3
科目 1 分數 : 100
科目 2 分數 : 72
科目 3 分數 : 92

學生人數1人
輸入新的學生資料 (y/n) ? y

輸入學生姓名: Vivin

學生: Vivin
-------------------
考試科目有幾科? : 2
科目 1 分數 : 92
科目 2 分數 : 81

學生人數2人
輸入新的學生資料 (y/n) ? n

班級清單

學生: Ken 成績:[100.0, 72.0, 92.0] 平均成績: 88.00  等第: B
學生: Vivin 成績:[92.0, 81.0] 平均成績: 86.50  等第: B

班級平均成績 87.25


## Numpy
+ 可做到的功能
  + 快速的多維陣列操作。
  + 可靠的科學功能函數庫。
  + 可協助繪圖工具進行繪圖。
+ NumPy 是幾乎每個科學 Python 應用程序或模組的核心，它提供了以向量化形式的快速 N-d 陣列類型可供操作。

In [7]:
a = [1,3,5,7,9]
print(a[2:4])
b = [[1,3,5,7,9],
     [2,4,6,8,10]]
print(b[0])
print(b[1][2:4])
c = [1,3,5,7,9]
d = [3,5,6,7,9]
f = c + d
print(f)
print(type(a),type(b),type(c),type(d))


[5, 7]
[1, 3, 5, 7, 9]
[6, 8]
[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]
<class 'list'> <class 'list'> <class 'list'> <class 'list'>


### Numpy 的陣列形狀!
+ NumPy 是同型態的多維陣列。
+ 透過一個正整數索引的元素表格進行規劃。
+ 透過 shape 指令可以知道陣列的形狀。

In [8]:
import numpy as np
a = np.array([1,3,5,7,9])
b = np.array([3,5,6,7,9])
c = a + b
print(c)
c = a - b
print(c)
print(type(c))

[ 4  8 11 14 18]
[-2 -2 -1  0  0]
<class 'numpy.ndarray'>


# Numpy 建立與計算

+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [14]:
import numpy as np
i = [[1,2,3],[2,3,4]]
a = np.array(i,dtype=np.uint16)
print(a)
print(type(a))

print("ndim:",a.ndim)
print("shape:",a.shape)
print("size:",a.size)
print("dtype",a.dtype)

[[1 2 3]
 [2 3 4]]
<class 'numpy.ndarray'>
ndim: 2
shape: (2, 3)
size: 6
dtype uint16


## 陣列初始化與重新規劃
+ 針對初始化這部分提供了多種方式：
+ 不做初始化
   + 例如：np.empty((2,4))
+ 全部規劃為 0
   + 例如：np.zeros((3,4))
+　全部規劃為 1
  + np.ones((5,2))
+ 全部規劃／填滿為某數，例如 6
   + 例如： np.full((3,3),6)
+ 建立對角矩陣，對角皆為 1，其他為 0
   + 例如： np.eye(3)
+ 建立對角矩陣，對角為 1,2,3,4，其他為 0
   + 例如： np.diag([1,2,3,4])
+ reshape((x,y)) 這個指令就可以將現有的陣列  重新規劃為 x 乘以 y 的陣列。 
+ np.arange(起始值, 結束值, 固定間隔)：也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自動化產生。
+ np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素。
+ arange(a,b,c)
   + 不包含 b 由 a 開始 以固定間隔 c 來取值
+ linspace(a,b,c,)
   + 包含 b 由 a 開始 切割成 c 個資料
+ linspace(a,b,c,endpoint=False)
   + 不包含 b 由 a 開始 切割成 c 個資料

### empty zeros ones

In [20]:
import numpy as np
x = np.empty((2,4))
print(x)
x = np.zeros((3,4))
print(x)
c = np.ones((5,5))
print(c)

[[4.67296746e-307 1.69121096e-306 1.42420753e-306 1.89146896e-307]
 [7.56571288e-307 3.11525958e-307 1.24610723e-306 1.29061142e-306]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### eye diag

In [23]:
import numpy as np
x = np.eye(3)
print(x)
x = np.diag([1,2,3,4])
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### linspace arange

In [29]:
import numpy as np
x = np.linspace(1,10,6)
print(x)
print("==============")
x = np.linspace(1,10,6).reshape(3,2)# (10-1)/(6-1)
print(x)
print("=============")
x = np.linspace(1,10,6,endpoint=False).reshape((3,2))#(10-1)/(6)
print(x)
print("=============")
x = np.arange(8).reshape(2,4)
print(x)
print("=============")
x = np.arange(8).reshape((4,2))
print(x)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
[[1.  2.5]
 [4.  5.5]
 [7.  8.5]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### Q1 . 請問以下的程式執行後值是多少?

In [30]:
import numpy as np
r1 = np.arange(25,30,.5)
print("r1=>",r1)

r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


### Q2 . 請問以下的程式執行後值是多少?

In [31]:
import numpy as np
lin = np.linspace(3,5,9)#5-3/9-1
print("lin=>",lin)

lin=> [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


## 陣列計算

In [35]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
c = a - b
print(a)
print(b)
print(c)
d = b ** 2
print("d=>",d)
f = np.array([5,-1,3,9,0])
print("f<=3",f<=3)
f[f <= 3] = 1
print(f)

[6 7 8 9]
[0 1 2 3]
[6 6 6 6]
d=> [0 1 4 9]
f<=3 [False  True  True False  True]
[5 1 1 9 1]


### Q. 請問以下的程式執行後值是多少?(選擇題)

In [36]:
import numpy as np
a = np.array([6,7,8,9])
a += 2
print(a)

[ 8  9 10 11]


## 陣列指定位置取值
+ 間隔選取 [::c]
  + 以 1 維陣列來說明 x[a:b:c]
  + a：選取資料的起始索引
  + b：選取資料的結束索引 +1
  + c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
+ 倒序 [::-1]
  + 只是單純的把順序反過來

## 陣列指定位置-給予一個整數
+ 關於指定位置  [row,column]
+ 假設給予一個整數為 N
 + 如果是給固定的 N，那就代表 row 或 column 等於 N。
 + 如果是 N：，那就代表 row 或 column 大於等於 N 的區域。
 + 如果是：N，那就代表 row 或 column 小於 N 的區域。 
 + 如果是：，那就代表 row 或 column 是任意欄位。

In [40]:
import numpy as np
a = np.array([[1,2,3],
              [3,6,9],
              [2,4,6]])
print(a)
print(a[0])
print(a[1,2])

[[1 2 3]
 [3 6 9]
 [2 4 6]]
[1 2 3]
9


In [45]:
import numpy as np
a = np.array([[1,2,3],
              [3,6,9],
              [2,4,6]])
print(a[1,1:3])
print(a[:,1])
a[1,2] = 7
print("================")
print(a)
print("================")
a[:,0] = [0,9,8]
print(a)

[6 9]
[2 6 4]
[[1 2 3]
 [3 6 7]
 [2 4 6]]
[[0 2 3]
 [9 6 7]
 [8 4 6]]


In [49]:
import numpy as np
a = np.array([[0,1,2,3,4,5],
       [10,11,12,13,14,15],
       [20,21,22,23,24,25],
       [30,31,32,33,34,35],
       [40,41,42,43,44,45],
       [50,51,52,53,54,55],
])
print("=====1====")
print(a[0,3:5])
print("=====2====")
print(a[4:,4:])
print("=====3====")
print(a[:3,:3])
print("=====4====")
print(a[:,2])

=====1====
[3 4]
=====2====
[[44 45]
 [54 55]]
=====3====
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
=====4====
[ 2 12 22 32 42 52]


## 陣列指定位置 - tuple 或 list
+ 如果是 tuple 方式，代表位置第一個 tuple 的每一個值為 row 的位置，第二個 tuple 的每一個值為 column 的位置。
+ 如果是 list 方式，代表 row 或 column 要選取 index 為 list 上的數值的資料。

In [50]:
import numpy as np
a = np.array([[0,1,2,3,4,5],
       [10,11,12,13,14,15],
       [20,21,22,23,24,25],
       [30,31,32,33,34,35],
       [40,41,42,43,44,45],
       [50,51,52,53,54,55],
])
print("==1===")
print(a[(0,1,2,3,4),(1,2,3,4,5)])

==1===
[ 1 12 23 34 45]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置


### 操作範例：reshape

In [56]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
b = a.reshape(3,2)
print(b)
a[0,1] = 100
print(b)#會改變
print(b.shape)
print(a.shape)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[  1 100]
 [  3   4]
 [  5   6]]
(3, 2)
(2, 3)


### resize

In [64]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print()
b = np.resize(a,(3,2))
print(b)
print(b.shape)
print()
a[0,1] = 100
print(b) #b不變
print(a.shape)
print(b.shape)
b = np.resize(a,(10,10))
print(b)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1 2]
 [3 4]
 [5 6]]
(2, 3)
(3, 2)
[[  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]
 [  5   6   1 100   3   4   5   6   1 100]
 [  3   4   5   6   1 100   3   4   5   6]
 [  1 100   3   4   5   6   1 100   3   4]]


### transpose

In [71]:
import numpy as np
newArray = np.arange(10).reshape(2,5)
print("==================")
print(newArray)
print("==================")
print(newArray.transpose())
print("==================")
print(newArray)## 原始陣列部會改變
tArray = newArray.T
print(tArray)
tArray[1] = 10
print("==================")
print(tArray)
print("==================")
print(newArray))#影響原始資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[ 0  5]
 [10 10]
 [ 2  7]
 [ 3  8]
 [ 4  9]]
[[ 0 10  2  3  4]
 [ 5 10  7  8  9]]


## 數值計算
+ 數值計算函數內放入參與計算的兩個陣列。
+ 進行計算的陣列第一維數量必須是相同。
+ add( ) 方法代表「加」，也可以使用「+」。
+ subtract( ) 方法代表「減」，也可以使用「-」。
+ multiply( )方法代表「乘」，也可以使用「*」。
+ divide( ) 方法代表「除」，也可以使用「/」。

### 加減運算

In [78]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([10,10,10])
c = np.add(a,b)
print(c)
d = np.subtract(a,b)
print(d)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


In [79]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])#(3,3)
b = np.array([10,10,10])#(3)
c = a + b
print(c)
d = a - b
print(d)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]


## 數值計算
+ np.power(a,n) 代表 a 陣列的 n 次方。
+ a 陣列的 n 次方也可以使用 a**n 方式表示。
+ N 可以是陣列，但兩陣列第一維數量必須是相同。
+ np. Reciprocal( ) 代表倒數的計算，倒數是指a*b=1，輸入 a 後求 b。 1/4的倒數是4

### Power計算

In [83]:
import numpy as np
a = np.array([4,5,6])
print(a)
b = np.power(a,2)
print(b)
c = np.array([1,2,3])
d = np.power(a,c)
print(d)
h = a ** c
print(h)

[4 5 6]
[16 25 36]
[  4  25 216]
[  4  25 216]


### reciprocal求倒數

In [84]:
import numpy as np
a = np.array([0.25,1.33,1,-0.1,100])
print(a)
print()
b = np.reciprocal(a) #倒數
print(b)

[  0.25   1.33   1.    -0.1  100.  ]

[  4.          0.7518797   1.        -10.          0.01     ]


## 除法計算與小數處理
+ np.mod( ) 方法內需加入兩個資料，例如 a 與 b，代表 a除以 b 的餘數。
+ np.remainder( ) 方法等同 np.mod( )。
+ np.around( ) 方法代表您要將浮點數資料整數位取四捨五入到第幾個位置，小數位取最接近的偶數，這個方法內需要兩個參數：
+ array：進行分析的陣列。
+ decimals小數位數：
  + 預設為 0。
  + 如果為正數，代表小數位數有幾個位子。
  + 如果為負數，代表小數點左邊的正整數將依序四捨五入進位。
+ np.floor( ) 方法代表回傳不大於輸入參數的最大整數。
+ np.ceil( ) 方法代表回傳大於輸入參數的最小整數。
+ 對於恰好介於四舍五入後的十進製值之間的值，NumPy會四舍五入為最接近的偶數值。因此，將1.5和2.5舍入為2.0，將-0.5和0.5舍入為0.0  

### 餘數Mod

In [86]:
import numpy as np
a = np.array([10,20,30])
b = np.array([3,5,7])
print(a)
print()
c = np.mod(a,b)
print(c)
print()
d = np.remainder(a,b)
print(d)


[10 20 30]

[1 0 2]

[1 0 2]


### around

In [89]:
import numpy as np
print(np.around([1.5,2.5],decimals=0))
print(np.around([1.51,2.51],decimals=0))
print(np.around([-0.5,0.5,0.567],decimals=0))

[2. 2.]
[2. 3.]
[-0.  0.  1.]


In [92]:
import numpy as np
a = np.array([1.0,5,5.45, 125,155, 0.56, 25.532])
b = np.around(a,decimals=2)
print(b)
b = np.around(a,decimals=-1)# 如果為負數，代表小數點左邊的正整數將依序四捨五入進位。
print(b)

[  1.     5.     5.45 125.   155.     0.56  25.53]
[  0.   0.  10. 120. 160.   0.  30.]
