In [2]:
import numpy as np
a = np.array([-1.7,1.5,-0.2,0.6,10])
print(a)
print()
b = np.floor(a)
print(b)
print()
c = np.ceil(a)
print(c)
print()

[-1.7  1.5 -0.2  0.6 10. ]

[-2.  1. -1.  0. 10.]

[-1.  2. -0.  1. 10.]



## 總和最大與最小
+ np.sum( ) 代表某一個陣列內容的總和，也可以指定這個陣列的哪一軸 (axis) 內容總和。
+ np.min( ) 代表某一個陣列內容的最小值，也可以指定這個陣列的哪一軸 (axis) 內容的最小值。
+ np.max( ) 代表某一個陣列內容的最大值，也可以指定這個陣列的哪一軸 (axis) 內容的最大值。
+ amin 與 min 是相同功能的方法。
+ amax 與 max 是相同功能的方法。

In [5]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
print("=====================")
b = np.sum(a)
print(b)
print("=====================")
b = np.sum(a,axis=0)
print(b)
print("=====================")
b = np.sum(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
300
[ 60 105 135]
[ 75 225]


### max() min()

In [10]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
print("=============================")
b = np.max(a)
print(b)
print("=============================")
b = np.max(a,axis=0)
print(b)
b = np.max(a,axis=1)
print(b)
print("=============================")
b = np.min(a,axis=0)
print(b)
b = np.min(a,axis=1)
print(b)

[[ 0 30 45]
 [60 75 90]]
90
[60 75 90]
[45 90]
[ 0 30 45]
[ 0 60]


## 中位數與平均
+ median( ) 方法可取出陣列或陣列中指定的軸之中位數。
+ 把所有值高低排序後找出正中間的一個作爲中位數。如果資料數量為偶數，則中位數取最中間的兩個數值的平均數。
+ 參數：
  + array：陣列
  + axis：軸
+ mean( ) 方法可取出陣列或陣列中指定的軸之平均數。
+ 平均值就是把陣列或指定軸的所有資料除以數量後的數值。
+ 參數：
    + array：陣列 
    + axis：軸
+ average( ) 方法與 mean( ) 方法相似，但可以加入權重進行計算。
+ 計算公式為 ((資料*權重)相加)/(權重相加)
+ 參數：
  + array：陣列
  + axis：軸
  + weights：權重，若沒有則設定為 1
  + returned：若設定為 true，代表返回計算結果跟權重相加總合兩筆資料，若沒有設定或設定  false 則只有計算結果 
+ 沒有指定權重時與一般平均值相同。
+ 加權平均值是由每個資料乘以權重以反映加上重要性因素後產生的平均值。
+ average( ) 使用時若沒有指定軸，則陣列將被平坦化。
+ 假設有個陣列資料為 [1,2,3,4]，相應的權重 [40,30,20,10]，加權平均數是這樣：
    (1x40+2x30+3x20+4x10)/(40+30+20+10)
  

In [13]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
b = np.median(a)# 6/2 = 3 取出 3與4編號的數字45與60 (45 + 60) /2
print(b)
print()
b = np.median(a,axis=0)
print(b)
print()
b = np.median(a,axis = 1)
print(b)
print()

[[ 0 30 45]
 [60 75 90]]
52.5

[30.  52.5 67.5]

[30. 75.]



In [15]:
import numpy as np
a = np.array([[0, 30,45],
              [60,75,90]])
print(a)
print()
b = np.mean(a)
print(b)
print()
b = np.mean(a,axis = 0)
print(b)
print()
b = np.mean(a,axis = 1)
print(b)
print()


[[ 0 30 45]
 [60 75 90]]

50.0

[30.  52.5 67.5]

[25. 75.]



## Numpy增減與統計

## 陣列附加資料
+ 這個方法動作將在陣列末端附加資料。
+ 若沒有指定軸 (維度) 則代表於陣列增加資料，陣列變成一維。
+ 維度必須相同
+ append 需要以下參數：
  + arr：想要附加資料的陣列。
  + values：想要附加於 arr 這個陣列後面的資料，資料的形狀必須與 arr 陣列相同。
  + axis：可以指定附加於哪一個軸 (維度) .

In [17]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
b = np.append(a,[7,8,9])
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 7 8 9]


In [21]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
print("==================================")
b = np.append(a,[[7,8,9]],axis = 0)
print(b)
b = np.append(a,[[7,8,9],[10,11,12]],axis = 0)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a)
d = np.append(a,[[7],[8]],axis = 1)
print(d)

[[1 2 3]
 [4 5 6]]
[[1 2 3 7]
 [4 5 6 8]]


## 陣列插入資料
+ 這個動作方法會依照指定的軸 (維度) 與指定的索引的陣列插入資料。
+ 如果沒有提到軸 (維度)，陣列將會變成一維。
+ insert( ) 函數需要以下參數：
  + arr：欲插入的陣列。
  + index：插入位置的索引值編號。
  + values：要插入的內容。
  + axis：指定的軸 (維度)，如果沒有給這參數，則會變成一維。

In [23]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
b = np.insert(a,3,[11,12])
print(b)


[[1 2]
 [3 4]
 [5 6]]
[ 1  2  3 11 12  4  5  6]


In [27]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print("===========================")
c = np.insert(a,1,[11],axis=0)
print(c)
print("===========================")
c = np.insert(a,1,[11,18],axis = 0)
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
[[ 1  2]
 [11 18]
 [ 3  4]
 [ 5  6]]


In [32]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print()
d = np.insert(a,1,11,axis = 1)
print(d)
print("========================")
d = np.insert(a,1,[11,18,17],axis = 1)
print(d)
d = np.insert(a,1,[11,18],axis = 1) 
print(d)

[[1 2]
 [3 4]
 [5 6]]

[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]
[[ 1 11  2]
 [ 3 18  4]
 [ 5 17  6]]


ValueError: could not broadcast input array from shape (2,1) into shape (3,1)

## 陣列刪除資料
+ 這個動作方法會依照指定的軸 (維度) 與指定的索引的陣列刪除資料。
+ 如果沒有提到軸 (維度)，陣列會以一維方式刪除指定位置資料。
+ Delete( ) 函數需要以下參數：
   + arr：欲刪除資料的陣列。
   + index：刪除資料位置的索引值編號。
   + axis：指定的軸(維度)，如果沒有給這參數，則會變成一維。

In [34]:
import numpy as np
a = np.array([[1,2],
              [3,4],
              [5,6]])
print(a)
print()
b = np.delete(a,3)
print(b)
b = np.delete(a,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 5 6]
[1 2 4 5 6]


In [35]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print( )
c = np.delete(a,1,axis = 0)
print(c)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]



In [36]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print( )
c = np.delete(a,1,axis = 1)
print(c)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]



## 讀存檔案
+ 可使用 np.loadtxt( ) 方法進行檔案的讀取。
+ 若不需要讀入第一列，可使用 skiprows=1 來忽略第一列。
+ 若我們的資料是利用 ‘,’ 當作資料與資料之間的分格符號，可使用 delimiter=‘ , ’ 設定，預設為空白。
+ 若設定 unpack=True 代表可以將 Column 分別切出來 (預設為False)。
+ 但是，當我們欲要讀的檔案，裡面有遺失值的時候，loadtxt 這個動作將會產生錯誤。loadtxt( ) 必須是在每一 row 都有相同數量的 value 下，才可以使用。
  + 建議改用 genfromtxt( ) 方法 ，它可以針對遺失值進行處理。
  + 參數加上 filling_values 可以把原本缺失的資料補上指定的資料。
+ 可利用 savetxt( ) 將資料存進檔案裡面保存。
+ genfromtxt 可透過 skip_header=1  參數忽略第一列。
+ 碰到遺失值的處理：
  + loadtxt 碰到遺失值會產生錯誤。
  + genfromtxt 碰到遺失值會以 nan 來表示。
+ genfromtxt 進行存取時：
  + 資料預設為浮點數(科學記數法)，所以建議儲存的時候以 fmt 進行格式設定。
  + 開啟時若資料為整數，請加入 dtype 設定為 int。

In [39]:
import numpy as np
x = np.loadtxt("data1.csv",skiprows = 1,delimiter=",")
print(x)
y,z = np.loadtxt('data1.csv',skiprows= 1,unpack = True,delimiter=',')
print("y:",y)
print("z:",z)

[[0.2 0.1]
 [0.4 0.5]
 [0.1 0.6]
 [0.1 0.3]
 [0.7 0.3]]
y: [0.2 0.4 0.1 0.1 0.7]
z: [0.1 0.5 0.6 0.3 0.3]


In [41]:
import numpy as np
# x = np.loadtxt('data2.csv',skiprows=1,delimiter=',')
# print(x)
x = np.loadtxt('data2.csv',skiprows=1,unpack=True,delimiter=',')
print(x)

ValueError: could not convert string to float: ''

In [49]:
import numpy as np
a = np.genfromtxt('data2.csv',delimiter=',',skip_header=1)
print(a)
np.savetxt('data1a.csv',a,delimiter=',',fmt="%1.4f")

b = np.genfromtxt('data2.csv',delimiter=",",skip_header=1,filling_values=0.001)
print(b)



[[0.2 0.1]
 [0.4 nan]
 [0.1 0.6]
 [0.1 0.3]
 [nan 0.3]]
[[0.2   0.1  ]
 [0.4   0.001]
 [0.1   0.6  ]
 [0.1   0.3  ]
 [0.001 0.3  ]]


In [58]:
import numpy as np
a = np.genfromtxt('data4.csv',dtype='uint16',delimiter=',',skip_header=1,encoding='utf-8')
print(a)
print(a.dtype)
print(a[0,0])
print(a[1,0])
print(a[2,1])

[[ 106    1 8397  364  209  291  398  516  524  630  633  608  615  713
   648  584  509  308  304  298  171   58   15    1]
 [ 106    2 8393  359  210  293  394  513  524  624  636  599  630  709
   649  584  515  303  302  300  174   59   15    1]
 [ 106    3 8389  353  219  283  397  509  530  617  635  602  636  707
   643  585  517  304  307  297  174   59   14    1]
 [ 106    4 8376  349  211  277  395  511  532  614  641  603  635  699
   647  586  519  304  305  297  175   61   14    1]
 [ 106    5 8378  352  218  273  395  512  526  610  642  602  638  687
   652  594  518  305  307  298  172   61   15    1]
 [ 106    6 8395  352  225  271  393  516  529  612  642  603  629  693
   656  597  516  308  306  297  174   59   16    1]
 [ 106    7 8411  363  220  276  387  518  529  611  650  602  619  699
   652  606  521  305  308  294  174   60   16    1]
 [ 106    8 8409  362  222  277  380  515  533  605  649  608  615  705
   646  607  529  301  309  295  177   57   16    1]


## 範圍與百分位數
+ np.ptp( ) 計算最大與最小值的差（最大 -(減) 最小）。
+ np.percentile( ) 方法代表百分位數，用於統計數據的度量指標，需要三個參數：
  + array：陣列。
  + percent：計算的百分位數，介於 0 到 100 之間。
  + axis：進行計算的軸。
+ 百分位數是一種位置量數，有助於瞭解資料在最小值與最大值之間的分布情況。
+ p- 百分位數表示：
  + 至少有 p-百分比 (p%) 的觀察值小於或者等於他。
  + 至少有 (100-p)% 的觀察值大於或等於他。
+ 計算方式：
  + 將資料由小到大排序。
  + 計算 i=(p%*樣本數) 之位置。
  + 於 i 位置：
    + a. 若不是整數，無條件進位取比 i 大的下一個整數位置的值。
    + b. 若為整數，則由 i 與 i+1 兩個位置上的值取平均。

In [60]:
import numpy as np
a = np.array([[0, 30,45],[60,75,90]])
print(a)
print( )
print(np.ptp(a))
b = np.ptp(a,axis = 0)
print(b)
print("===================")
b = np.ptp(a,axis = 1)
print(b)

[[ 0 30 45]
 [60 75 90]]

90
[60 45 45]
[45 30]


In [65]:
import numpy as np
arry = np.array([4,6,10,12,8])
# 1 2 3 4  5
# 4 6 8 10 12
# n = 長度
# 1 + (n + 1) * p
# 1 + (5 + 1) * 0.5 
b = np.percentile(arry,50)
print("percentile is:",b)
a = np.array([[11,8,9],
              [5,4,1]])
#1 2 3 4 5  6
#1 4 5 8 9 11
# 1 + (6 - 1) *0.25 = 2.25
# 4 + (5 - 4) * 0.25 = 4.25
b = np.percentile(a,25)
print(b)
# 1 2  
# 5 11
# 1 +(2-1) * 0.5 = 1.5
#5 + (11 - 5) * 0.5 = 8
b = np.percentile(a,50,axis=0)
print(b)
# 1 2 3
# 8 9 11
#1 + (3 - 1) * 0.5 = 2
b = np.percentile(a,50,axis=1)
print(b)

percentile is: 8.0
4.25
[8. 6. 5.]
[9. 4.]


## 變異數與標準差
+ 變異數代表所有資料到平均數的距離之平方。
+ 標準差代表變異數開平方根，也就是可依此表示資料的分散程度。
+ var( ) 代表由陣列取得變異數的方法。
+ std( ) 代表由陣列取得標準差的方法。

In [69]:
import math
import numpy as np
a = np.array([1,2,3,4])
print(a)
# 1 + 2+ 3+ 4 = 10
# 10 / 4 = 2.5 均值:2.5
mean = a .mean()
var = ((a - mean) ** 2).mean()
print(var)#變異數
print(math.sqrt(var))#標準差
b = np.var(a)
print(b)#變異數
b = np.std(a)
print(b)#標準差

[1 2 3 4]
1.25
1.118033988749895
1.25
1.118033988749895
